import uuid
from datetime import datetime


def now():
    return datetime.now().strftime('%Y-%m-%dT%H:%M:%SZ')


def create_template(name, description):
    created_on = now()
    return {
        "@type": "https://schema.metadatacenter.org/core/Template",
        "@context": {
            "xsd": "http://www.w3.org/2001/XMLSchema#",
            "pav": "http://purl.org/pav/",
            "bibo": "http://purl.org/ontology/bibo/",
            "oslc": "http://open-services.net/ns/core#",
            "schema": "http://schema.org/",
            "schema:name": {
                "@type": "xsd:string"
            },
            "schema:description": {
                "@type": "xsd:string"
            },
            "pav:createdOn": {
                "@type": "xsd:dateTime"
            },
            "pav:createdBy": {
                "@type": "@id"
            },
            "pav:lastUpdatedOn": {
                "@type": "xsd:dateTime"
            },
            "oslc:modifiedBy": {
                "@type": "@id"
            }
        },
        "type": "object",
        "title": "{0} template schema".format(name),
        "description": "{0} template schema generated by the CEDAR Template Editor 1.6.3".format(name),
        "_ui": {
            "pages": [],
            "order": [],
            "propertyLabels": {},
            "propertyDescriptions": {}
        },
        "properties": {
            "@context": {
                "type": "object",
                "properties": {
                    "rdfs": {
                        "type": "string",
                        "format": "uri",
                        "enum": [
                            "http://www.w3.org/2000/01/rdf-schema#"
                        ]
                    },
                    "xsd": {
                        "type": "string",
                        "format": "uri",
                        "enum": [
                            "http://www.w3.org/2001/XMLSchema#"
                        ]
                    },
                    "pav": {
                        "type": "string",
                        "format": "uri",
                        "enum": [
                            "http://purl.org/pav/"
                        ]
                    },
                    "schema": {
                        "type": "string",
                        "format": "uri",
                        "enum": [
                            "http://schema.org/"
                        ]
                    },
                    "oslc": {
                        "type": "string",
                        "format": "uri",
                        "enum": [
                            "http://open-services.net/ns/core#"
                        ]
                    },
                    "skos": {
                        "type": "string",
                        "format": "uri",
                        "enum": [
                            "http://www.w3.org/2004/02/skos/core#"
                        ]
                    },
                    "skos:notation": {
                        "type": "object",
                        "properties": {
                            "@type": {
                                "type": "string",
                                "enum": [
                                    "xsd:string"
                                ]
                            }
                        }
                    },
                    "rdfs:label": {
                        "type": "object",
                        "properties": {
                            "@type": {
                                "type": "string",
                                "enum": [
                                    "xsd:string"
                                ]
                            }
                        }
                    },
                    "schema:isBasedOn": {
                        "type": "object",
                        "properties": {
                            "@type": {
                                "type": "string",
                                "enum": [
                                    "@id"
                                ]
                            }
                        }
                    },
                    "schema:name": {
                        "type": "object",
                        "properties": {
                            "@type": {
                                "type": "string",
                                "enum": [
                                    "xsd:string"
                                ]
                            }
                        }
                    },
                    "schema:description": {
                        "type": "object",
                        "properties": {
                            "@type": {
                                "type": "string",
                                "enum": [
                                    "xsd:string"
                                ]
                            }
                        }
                    },
                    "pav:createdOn": {
                        "type": "object",
                        "properties": {
                            "@type": {
                                "type": "string",
                                "enum": [
                                    "xsd:dateTime"
                                ]
                            }
                        }
                    },
                    "pav:derivedFrom": {
                        "type": "object",
                        "properties": {
                            "@type": {
                                "type": "string",
                                "enum": [
                                    "@id"
                                ]
                            }
                        }
                    },
                    "pav:createdBy": {
                        "type": "object",
                        "properties": {
                            "@type": {
                                "type": "string",
                                "enum": [
                                    "@id"
                                ]
                            }
                        }
                    },
                    "pav:lastUpdatedOn": {
                        "type": "object",
                        "properties": {
                            "@type": {
                                "type": "string",
                                "enum": [
                                    "xsd:dateTime"
                                ]
                            }
                        }
                    },
                    "oslc:modifiedBy": {
                        "type": "object",
                        "properties": {
                            "@type": {
                                "type": "string",
                                "enum": [
                                    "@id"
                                ]
                            }
                        }
                    }
                },
                "required": [
                    "xsd",
                    "pav",
                    "schema",
                    "oslc",
                    "schema:isBasedOn",
                    "schema:name",
                    "schema:description",
                    "pav:createdOn",
                    "pav:createdBy",
                    "pav:lastUpdatedOn",
                    "oslc:modifiedBy"
                ],
                "additionalProperties": False
            },
            "@id": {
                "type": [
                    "string",
                    "null"
                ],
                "format": "uri"
            },
            "@type": {
                "oneOf": [
                    {
                        "type": "string",
                        "format": "uri"
                    },
                    {
                        "type": "array",
                        "minItems": 1,
                        "items": {
                            "type": "string",
                            "format": "uri"
                        },
                        "uniqueItems": True
                    }
                ]
            },
            "schema:isBasedOn": {
                "type": "string",
                "format": "uri"
            },
            "schema:name": {
                "type": "string",
                "minLength": 1
            },
            "schema:description": {
                "type": "string"
            },
            "pav:createdOn": {
                "type": [
                    "string",
                    "null"
                ],
                "format": "date-time"
            },
            "pav:derivedFrom": {
                "type": "string",
                "format": "uri"
            },
            "pav:createdBy": {
                "type": [
                    "string",
                    "null"
                ],
                "format": "uri"
            },
            "pav:lastUpdatedOn": {
                "type": [
                    "string",
                    "null"
                ],
                "format": "date-time"
            },
            "oslc:modifiedBy": {
                "type": [
                    "string",
                    "null"
                ],
                "format": "uri"
            }
        },
        "required": [
            "@context",
            "@id",
            "schema:isBasedOn",
            "schema:name",
            "schema:description",
            "pav:createdOn",
            "pav:createdBy",
            "pav:lastUpdatedOn",
            "oslc:modifiedBy"
        ],
        "schema:name": name,
        "schema:description": description,
        "pav:createdOn": created_on,
        "pav:createdBy": None,
        "pav:lastUpdatedOn": created_on,
        "oslc:modifiedBy": None,
        "schema:schemaVersion": "1.6.0",
        "additionalProperties": False,
        "pav:version": "0.0.1",
        "bibo:status": "bibo:draft",
        "$schema": "http://json-schema.org/draft-04/schema#"
    }


def create_element(name, description, identifier):
    created_on = now()
    return {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "@id": None,
        "@type": "https://schema.metadatacenter.org/core/TemplateElement",
        "@context": {
            "xsd": "http://www.w3.org/2001/XMLSchema#",
            "pav": "http://purl.org/pav/",
            "bibo": "http://purl.org/ontology/bibo/",
            "oslc": "http://open-services.net/ns/core#",
            "schema": "http://schema.org/",
            "schema:name": {
                "@type": "xsd:string"
            },
            "schema:description": {
                "@type": "xsd:string"
            },
            "pav:createdOn": {
                "@type": "xsd:dateTime"
            },
            "pav:createdBy": {
                "@type": "@id"
            },
            "pav:lastUpdatedOn": {
                "@type": "xsd:dateTime"
            },
            "oslc:modifiedBy": {
                "@type": "@id"
            }
        },
        "type": "object",
        "title": "{0} element schema".format(name),
        "description": "{0} element schema generated by the CEDAR Template Editor 2.6.16".format(name),
        "_ui": {
            "order": [],
            "propertyLabels": {},
            "propertyDescriptions": {}
        },
        "properties": {
            "@context": {
                "type": "object",
                "properties": {},
                "additionalProperties": False,
                "required": []
            },
            "@id": {
                "type": "string",
                "format": "uri"
            },
            "@type": {
                "oneOf": [
                    {
                        "type": "string",
                        "format": "uri"
                    },
                    {
                        "type": "array",
                        "minItems": 1,
                        "items": {
                            "type": "string",
                            "format": "uri"
                        },
                        "uniqueItems": True
                    }
                ]
            }
        },
        "schema:name": name,
        "schema:description": description,
        "required": [
            "@context",
            "@id"
        ],
        "pav:createdOn": created_on,
        "pav:createdBy": None,
        "pav:lastUpdatedOn": created_on,
        "oslc:modifiedBy": None,
        "schema:schemaVersion": "1.6.0",
        "additionalProperties": False,
        "pav:version": "0.0.1",
        "bibo:status": "bibo:draft"
    }


def create_field(name, description, identifier):
    created_on = now()
    return {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "@id": None,
        "@type": "https://schema.metadatacenter.org/core/TemplateField",
        "@context": {
            "xsd": "http://www.w3.org/2001/XMLSchema#",
            "pav": "http://purl.org/pav/",
            "bibo": "http://purl.org/ontology/bibo/",
            "oslc": "http://open-services.net/ns/core#",
            "schema": "http://schema.org/",
            "skos": "http://www.w3.org/2004/02/skos/core#",
            "schema:name": {
                "@type": "xsd:string"
            },
            "schema:description": {
                "@type": "xsd:string"
            },
            "skos:prefLabel": {
                "@type": "xsd:string"
            },
            "skos:altLabel": {
                "@type": "xsd:string"
            },
            "pav:createdOn": {
                "@type": "xsd:dateTime"
            },
            "pav:createdBy": {
                "@type": "@id"
            },
            "pav:lastUpdatedOn": {
                "@type": "xsd:dateTime"
            },
            "oslc:modifiedBy": {
                "@type": "@id"
            }
        },
        "type": "object",
        "title": "{0} field schema".format(name),
        "description": "{0} field schema generated by the CEDAR Template Editor 2.6.16".format(name),
        "_ui": {
            "inputType": "textfield"
        },
        "_valueConstraints": {
            "requiredValue": False
        },
        "properties": {
            "@type": {
                "oneOf": [
                    {
                        "type": "string",
                        "format": "uri"
                    },
                    {
                        "type": "array",
                        "minItems": 1,
                        "items": {
                            "type": "string",
                            "format": "uri"
                        },
                        "uniqueItems": True
                    }
                ]
            },
            "@value": {
                "type": [
                    "string",
                    "null"
                ]
            },
            "rdfs:label": {
                "type": [
                    "string",
                    "null"
                ]
            }
        },
        "required": [
            "@value"
        ],
        "schema:name": name,
        "schema:description": description,
        "pav:createdOn": created_on,
        "pav:createdBy": None,
        "pav:lastUpdatedOn": created_on,
        "pav:version": "0.0.1",
        "bibo:status": "bibo:draft",
        "oslc:modifiedBy": None,
        "schema:schemaVersion": "1.6.0",
        "additionalProperties": False
    }
